#clear workspace
rm(list = ls())
#parse soil spreadsheets. Need sample id, horizon, soil temp, sample bottom - sample top, soil sampling device, drymassboatmass - boatmass, soil carbon percentage(per plot maybe)
setwd("~/Desktop/NEON/NEON_soil-periodic/NEONSoilBio")
SOILCHEM19 <- read.csv(file='NEONSOILCHEM2019.csv')
SOILCHEM14 <- read.csv(file='NEONSOILCHEM2014.csv')
SOILCHEM14 <- SOILCHEM14[complete.cases(SOILCHEM14[,18]),]
SOILCHEM <- rbind(SOILCHEM19, SOILCHEM14)
SOILCORE16 <- read.csv(file='NEONSOILCORE2016ALL.csv')
SOILMASS16 <- read.csv(file='NEONSOILMASS2016ALL.csv')
SOIL2016<- merge(x=SOILCORE16, y=SOILMASS16, by = "sampleID", all.x= TRUE, all.y = TRUE, header = TRUE)
SOIL2016 <- subset(SOIL2016, select = c("sampleID", "plotID.x", "horizon.x","sampleTopDepth", "sampleBottomDepth", "boatMass", "dryMassBoatMass", "soilSamplingDevice"))
SOIL2016 <- cbind(SOIL2016, (SOIL2016$sampleBottomDepth - SOIL2016$sampleTopDepth))
SOIL2016 <- cbind(SOIL2016, (SOIL2016$dryMassBoatMass - SOIL2016$boatMass))
SOIL2016 <- SOIL2016 %>% rename( "SOILDepth" = `(SOIL2016$sampleBottomDepth - SOIL2016$sampleTopDepth)`)
SOIL2016 <- SOIL2016 %>% rename( "SoilMass" = `(SOIL2016$dryMassBoatMass - SOIL2016$boatMass)`)
#Calculate plot average c percentage for O and M soils
Meanchem <- SOILCHEM %>% group_by(plotID, horizon) %>% summarise(mean(organicCPercent))
SOIL2016<- merge(x=SOIL2016, y=Meanchem, by.x=c("plotID.x", "horizon.x"), by.y=c("plotID", "horizon"), all.x= TRUE, header = TRUE)
#soil sampling device volume(might be wrong)
corer_2016 <- as.data.frame(ifelse(SOIL2016$soilSamplingDevice == 'corer', 20.27, 100))
SOIL2016 <- cbind(SOIL2016, corer_2016)
SOIL2016 <- SOIL2016 %>% rename( "deviceVolume" = `ifelse(SOIL2016$soilSamplingDevice == "corer", 20.27, 100)`)
#soil bulk denisty = mass/volume(defintiely wrong)
bulkdens_2016 <- as.data.frame(SOIL2016$SoilMass / SOIL2016$deviceVolume)
